name: Compilar

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Compilar
        run: ./gradlew build libreforgeJar --no-daemon

      - name: Listar jars generados
        run: find . -name "*.jar" -not -path "./.gradle/*" -not -path "./gradle/*" -exec ls -lh {} \;

      - uses: actions/upload-artifact@v4
        with:
          name: EcoBattlepass
          path: |
            bin/*.jar
            **/build/libs/*.jar
